export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_USERS = 'SET_USERS';
export const ADD_USER = 'ADD_USER';
export const USER_FETCHED = 'USER_FETCHED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER_ID = 'SET_USER_ID';

export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DOCUMENT_FETCHED = 'DOCUMENT_FETCHED';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SET_PAGINATION = 'SET_DOCUMENTPAGINATION';
